version: "3.6"
services:
  server:
    image: dockergelb/spoton
    depends_on:
      - client
    working_dir: /server
    volumes:
      - ./db:/server/db
      - ./public:/client
    build:
      context: ../server
      dockerfile: ../docker/server.dockerfile
    env_file: "./.env"
    ports:
      - 8080:8080

  client:
    working_dir: /client
    volumes:
      - ./public:/client/out/
    build:
      context: ../client
      dockerfile: ../docker/client.dockerfile
